# Generated by Django 4.1.4 on 2023-07-12 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_app', '0003_notification_notification_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='rooms_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
