# Generated by Django 4.1.4 on 2023-07-12 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_app', '0005_remove_room_users_room_doctor_room_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='room',
            name='patient',
        ),
        migrations.AddField(
            model_name='room',
            name='room_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='room_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
