# Generated by Django 4.1.4 on 2023-07-13 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_app', '0007_chatnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_users',
        ),
        migrations.AddField(
            model_name='room',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
